site_name: rcmedeiros/saphira
site_description:
      A TBD
repo_url: https://github.com/rcmedeiros/saphira/
edit_uri: edit/develop/mkdocs
dev_addr: 127.0.0.1:80

docs_dir: mkdocs
site_dir: docs

markdown_extensions:
      - nl2br
      - codehilite:
              linenums: None
              noclasses: false
              guess_lang: False
              css_class: codehilite
              use_pygments: True
              pygments_style: monokai
      - smarty:
              smart_angled_quotes: True
      - admonition
      - abbr
      - def_list
      - footnotes
      - attr_list
      - toc
nav:
      - Home: index.md
theme: material
extra_css:
      - css/theme.css
      - css/codehilite.css